<?xml version="1.0"?>
<xsl:stylesheet version="1.1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text"/>
  <xsl:template match="/script-interface">
<xsl:text><![CDATA[
// Generated by script-header.xsl
// DO NOT EDIT
]]></xsl:text>
    <xsl:for-each select="type">
      <xsl:if test="cppwrap">
        class <xsl:value-of select="cppwrap" />;
        extern Scriptix::Value toValue(const <xsl:value-of select="cppwrap"/>&amp; data);
      </xsl:if>
    </xsl:for-each>
    Scriptix::Value toValue(const Scriptix::Value&amp; value) { return value; }
<xsl:text>
</xsl:text>
  </xsl:template>
</xsl:stylesheet>
<!-- vim: set filetype=xml tabstop=2 shiftwidth=2 expandtab: -->
